/*
-- Query: SELECT * FROM psersonalprojet.info
LIMIT 0, 1000

-- Date: 2023-01-27 18:12
*/
INSERT INTO `` (`no`,`title`,`main`,`writer`) VALUES (1,'두면도서관 이용시간 안내','1. 이용시간(도서관 정상 운영 시) \n * 종합자료실 : 평일(화-금) 09:00 ~ 20:00 | 토,일요일 09:00 ~ 17:00\n * 어린이자료실 : 평일(화-금) 09:00 ~ 18:00 | 토,일요일 09:00 ~ 17:00\n * 디지털코너 : 평일(화-금) 09:00 ~ 20:00 | 토,일요일 09:00 ~ 17:00\n * 다문화자료실 : 평일(화-금) 09:00 ~ 18:00 | 토,일요일 09:00 ~ 17:00\n * 종합열람실 : 주말 및 평일(화-일) 06:00 ~ 22:00 | 월요일 제외\n2. 휴관일안내\n * 일요일을 제외한 관공서 공휴일(단, 일요일과 공휴일이 겹치는 경우 휴관)\n * 매주 월요일\n * 특별한 사유로 인하여 관장이 지정한 날','관리자');
INSERT INTO `` (`no`,`title`,`main`,`writer`) VALUES (2,'시설 안내','1. 휴게공간\n * 지하1층 문화누리터 앞 휴게공간(도시락 이용 가능)\n * 4층 중정 휴게공간(도시락 이용 가능)\n \n2. 도시락존\n * 지하 1층 휴게공간, 4층 중정 휴게공간\n * 도시락 및 간단한 음식 이용 가능\n \n3. 유아휴게실(수유실)\n * 1층 어린이자료실(유아실) 내 위치\n \n4. 사물함존\n * 지상5층 위치(126개)\n * 분기별 신청 후 이용\n \n5. 주차장\n 1) 주차장 요금\n    * 1시간까지 : 무료\n    * 1시간 초과 : 최초 30분까지 600원, 10분 초과마다 300원	\n    * 전일주차 : 6,900원\n    * 주차요금은 인천광역시교육감 소관 부설주차장 사용료 징수 조례 별표의 2급지를 기준으로 하여 일부 조정함.\n    * 5시간 이상 주차시에는 전일주차 요금을 징수함.\n    \n 2) 민원(방문)차량 승용차 요일제\n    * 월 : 1ㆍ6\n    * 화 : 2ㆍ7\n    * 수 : 3ㆍ8\n    * 목 : 4ㆍ9\n    * 금 : 5ㆍ0\n    * 공휴일 비근무일(토,일) : -\n    * 적용 제외가능 차량\n        : 경차(1000cc미만), 장애인 사용승용차, 긴급자동차, 보도용자동차, 외교용자동차, 군용자동차, 경호용자동차등 (관용차량중 기관 운영상 주요 업무수행 차량 포함)\n          회물자동차, 특수자동차, 승합자동차, 하이브리드자동차 등','관리자');
INSERT INTO `` (`no`,`title`,`main`,`writer`) VALUES (3,'편의시설 사용 안내','1. 무선인터넷\n - 대상 : 무선 랜카드를 장착한 노트북 및 PDA\n - 지원규격 : 무선랜 802.11b(11M) / 802.11g(54M) 둘다 지원 가능\n - 설정방법 : Windows 네트워크환경->TCP/IP 프로토콜에서 “자동으로 IP 주소받기”,“자동으로 DNS서버 주소받기”로 선택하면 자동으로 설정값이 적용되어 사용가능\n - 비밀번호 : 무선인터넷 비밀번호는 안내데스크, 자료실 직원에게 암호키값을 받아 사용\n\n2. 사물함\n - 4층 복도 유료사물함 : 64칸(월 사용료: 9,000원/ 연락처:010-9250-7514 스타박스)\n\n3. 복사/출력 시설\n - 자료복사 : 종합자료실(2층) 디지털·특허정보자료실(3층)\n - 자료출력 : 디지털·특허정보자료실(3층)\n - 이용시간 : 자료실 운영시간과 동일\n - 이용방법 : 카드 방식(신용, 체크, 티머니 등)의 복사기 운영\n - 복사단가 : 흑백 A4 40원, B4 50원 / 컬러 A4 100원, B4 150원\n\n4. 스캔시설\n- 설치장소 : 3층 디지털·특허정보자료실\n- 스캔가능 PC : 2대 (29번, 30번)','관리자');
INSERT INTO `` (`no`,`title`,`main`,`writer`) VALUES (5,'wgfg','\n			@Override\n			public void actionPerformed(ActionEvent e) {\n				// TODO Auto-generated method stub\n				\n				try {\n					//삭제하기\n					if(ntxt.getText().equals(\"\")) {\n						JOptionPane.showMessageDialog(null, \"삭제를 원하는 공지사항의 번호를 기재해 주세요\", \"기재 누락\", JOptionPane.WARNING_MESSAGE);\n					} else {\n						ResultSet srs = stmt.executeQuery(\"select * from info where no = +ntxt.getText()+;\");\n						if(srs.next()) {\n							stmt.executeUpdate(\"delete from info where no = +ntxt.getText()+;\");\n							System.out.println(\"delete from info where no = +ntxt.getText()+;\");\n							JOptionPane.showMessageDialog(null, \"공지사항 삭제가 완료되었습니다.\", \"공지 삭제\", JOptionPane.PLAIN_MESSAGE);\n							setVisible(false);\n							jframe.setVisible(false);\n							Admin_info adinfo = new Admin_info(stmt, id);\n						} else {\n							JOptionPane.showMessageDialog(null, \"존재하지 않는 번호입니다. \n 번호를 확인해 주세요.\", \"번호 입력 오류\", JOptionPane.ERROR_MESSAGE);\n						}\n					}\n				} catch (SQLException e1) {\n					// TODO Auto-generated catch block\n					e1.printStackTrace();','관리자');
INSERT INTO `` (`no`,`title`,`main`,`writer`) VALUES (6,'ddd','1. 이용시간(도서관 정상 운영 시) \n * 종합자료실 : 평일(화-금) 09:00 ~ 20:00 | 토,일요일 09:00 ~ 17:00\n * 어린이자료실 : 평일(화-금) 09:00 ~ 18:00 | 토,일요일 09:00 ~ 17:00\n * 디지털코너 : 평일(화-금) 09:00 ~ 20:00 | 토,일요일 09:00 ~ 17:00\n * 다문화자료실 : 평일(화-금) 09:00 ~ 18:00 | 토,일요일 09:00 ~ 17:00\n * 종합열람실 : 주말 및 평일(화-일) 06:00 ~ 22:00 | 월요일 제외\n\n2. 휴관일안내\n * 일요일을 제외한 관공서 공휴일(단, 일요일과 공휴일이 겹치는 경우 휴관)\n * 매주 월요일\n * 특별한 사유로 인하여 관장이 지정한 날','관리자');
